site_name: DOSAR Outreach Materials
site_url: https://opensciencegrid.github.io/dosar
repo_url: https://github.com/opensciencegrid/dosar
theme: readthedocs

pages:
- Home: 'index.md'
- Current or Upcoming Events:
  - 'Data Trieste 2019 Schedule': 
  - 'Data Trieste 2019 Materials': 
- Past Events:
  - 'Data Sao Paulo 2018 Schedule': 'DataSaoPaulo2018/School.md'
  - 'Data Sao Paulo 2018 Materials': 'DataSaoPaulo2018/Materials.md'
  - 'Data Kigali 2018 Schedule': 'DataKigali2018/School.md'
  - 'Data Kigali 2018 Materials': 'DataKigali2018/Materials.md'
  - 'Data Trieste 2018 Schedule': 'DataTrieste2018/School.md'
  - 'Data Trieste 2018 Materials': 'DataTrieste2018/Materials.md'
  - 'ASP 2018 Schedule': 'ASP2018/ASP2018_Schedule.md'
  - 'ASP 2018 Material': 'ASP2018/ASP2018_Materials.md'
  - 'Data Sao Paulo Schedule': 'Materials/DSP_DT2017.md'
  - 'Data Sao Paulo Materials': 'Materials/DSP_Materials.md' 
  - 'Polar Hackathon Schedule': 'Materials/PH_DT2017.md'
  - 'Polar Hackathon Materials': 'Materials/PH_Materials.md'
- DOSAR Video Meetings:
  - 'October 24, 2018': 'Meetings/24October2018.md'
  - 'March 12, 2019': 'Meetings/12March2019.md'


markdown_extensions:
  - admonition
  - osg_markdown.colors
